### ISSUE TITLE
Open the app = black screen, Crashes on big games, Keymapper non-existent, fullscreen is broken

### ISSUE THREAD

**Issue by ghost** [clchiou/chrome-dosbox#10]
## @clchiou Hello, Can you please fix the bugs in your program?
I am using DOSBOX on a chromebook to play old Dos games like Simcity 2000, Elite I and II and DOOM but the application keeps crashing on DOOM and Simcity 2000.
Normally on a fresh install, dosbox crashes or is a black screen, using my config file I can get Elite I and II running and dosbox shows what command I am typing etc.

#### My config file:
```
# DOSBox configuration file

[sdl]
fullscreen=true
fulldouble=false
windowresolution=1366x768
fullresolution=desktop
output=overlay
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true

[dosbox]
language=
machine=svga_paradise
captures=none
memsize=512

[render]
frameskip=0
aspect=false
scaler=2xsai

[cpu]
core=auto
cputype=auto
cycles=20000
cycleup=500
cycledown=500

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=default
midiconfig=

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[gus]
gus=false
gusrate=44100
gusbase=240
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[speaker]
pcspeaker=false
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[joystick]
joysticktype=auto
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[ipx]
ipx=false

[autoexec]
cd DOSBOX
```

When I try to activate the keymapper the program crashes, I need to access the keymapper because the right shift key in Elite II (It slows down my spaceship) doesn't work

Fullscreen also is another problem, it doesn't work and I don't want to play games on a tiny window..

Thank you for your time @clchiou , and hope you can fix it soon.

**Comment by clchiou** [comment]
Hi, thanks for reporting this bug. Unfortunately I am no longer working on this project.

**Comment by ghost** [comment]
Awww, you aren't? Well awesome job tho, this application is a really good port!
