### ISSUE TITLE
mouse pointer tracking touchpad out of sync

### ISSUE THREAD

**Issue by wmwragg** [clchiou/chrome-dosbox#3]
I installed version 0.1.5 and got elite and elite plus running fine. I then got frontier up and running, and it mostly runs OK except for being a bit laggy sometimes, but the mouse pointer in the game appears along with the chromebook pointer, and they don't track together. So the chrome pointer might hit the edge of the screen while the game pointer is in the middle of the screen, and sometimes the game pointer just stops as if it has hit the edge of the screen, but is still not at the edge of the screen. I tried autolock=true, in the settings, but that had no effect. Any ideas?

Details:

Version 36.0.1985.49 beta
Platform 5841.30.0 (Official Build) beta-channel daisy_spring
Firmware Google_Spring.3824.129.0

On an HP Chromebook 11

Anything I can help with just shout, and cheers for putting all the work in to making a port for Chromebooks.

**Comment by clchiou** [comment]
On Fri, Jul 4, 2014 at 5:06 AM, William Wragg notifications@github.com
wrote:

> I installed version 0.1.5 and got elite and elite plus running fine. I
> then got frontier up and running, and it mostly runs OK except for being a
> bit laggy sometimes, but the mouse pointer in the game appears along with
> the chromebook pointer, and they don't track together. So the chrome
> pointer might hit the edge of the screen while the game pointer id in the
> middle of the screen, and sometimes the game pointer just stops as if it
> has hit the edge of the screen, but is still not at the edge of the screen.
> I tried autolock=true, in the settings, but that had no effect. Any ideas?
> 
> I experience the laggy problem, too. Just don't have time to fix that :(

I don't quite understand the mouse pointer problem. Could you be more
elaborate on that please?

**Comment by wmwragg** [comment]
The lag is OK, it's much better than it was the first time I tried it, and it is mostly playable, so I wouldn't worry about that too much. As for the mouse issue, I'll try to describe it in more detail:

On the screen I end up with **both** the Chrome OS mouse pointer, **and** the Frontier games mouse pointer, but they appear to travel at different speeds. So as I move my fingers across the trackpad, the Chrome OS pointer moves faster than the Frontier games pointer. That's one of the issues. The other is that the Frontier games pointer seems to stop as though it has hit the edge of the screen, but the Frontier games pointer is still in the middle of the screen, and the Chrome OS pointer is not at the edge of the screen either. The point on the screen which this happens seems to vary, from time to time. The problem with this is, that the Frontier games pointer cannot get to certain parts of the screen, especially the parts near the edges of the screen.

It's a bit difficult to describe, so if you need further help let me know. I can supply you with the shareware version of the Frontier game if you require it for testing purposes. Frontier games released the version for free on their site a few years ago.

**Comment by clchiou** [comment]
On Fri, Jul 11, 2014 at 3:19 AM, William Wragg notifications@github.com
wrote:

> The lag is OK, it's much better than it was the first time I tried it, and
> it is mostly playable, so I wouldn't worry about that too much. As for the
> mouse issue, I'll try to describe it in more detail:
> 
> On the screen I end up with _both_ the Chrome OS mouse pointer, _and_ the
> Frontier games mouse pointer, but they appear to travel at different
> speeds. So as I move my fingers across the trackpad, the Chrome OS pointer
> moves faster than the Frontier games pointer. That's one of the issues. The
> other is that the Frontier games pointer seems to stop as though it has hit
> the edge of the screen, but the Frontier games pointer is still in the
> middle of the screen, and the Chrome OS pointer is not at the edge of the
> screen either. The point on the screen which this happens seems to vary,
> from time to time. The problem with this is, that the Frontier games
> pointer cannot get to certain parts of the screen, especially the parts
> near the edges of the screen.
> 
> I see. Thank you for the detailed description. I will see if I can fix
> this problem.

By the way, you mentioned about trackpad. Did you encounter the same
problem if you use a mouse instead?

**Comment by wmwragg** [comment]
I'm afraid I don't have a mouse, but I'll see if I can get hold of one and I'll let you know the outcome.

**Comment by dereckson** [comment]
Problem is identical with a touchpad or an external mouse.

It occurs when the screen is maximized, but not when it's windowed in 1x display mode.

This is a severe blocker for some games requiring some precision or timing, like Space Quest.

**Comment by koalaman** [comment]
I had the same problem -- not being able to reach parts of the screen with the in-game cursor. I worked around it by adding `sensitivity=200` to the config so that the in-game cursor would move faster than the OS cursor. Now I can move the in-game cursor to any point on game screen without the OS cursor leaving the window.

**Comment by clchiou** [comment]
Nice hack!

**Comment by koalaman** [comment]
It works but it would be way better if I could get DosBox to hide the OS cursor, because I currently see both at the same time (with or without this hack) which is pretty distracting. Is there a way to do that? I tried the `autolock = true` option but it didn't do anything on my ChromeOS Pixel 2.

**Comment by clchiou** [comment]
If I understand you correctly, we could set CSS style `cursor: none;` to
hide mouse cursor when the cursor moves on top of the DOM element for the
DOSBox but that require an software update. If you just want a quick hack,
you could open Chrome's developer tools and add that that style (and see
whether you like to hide the cursor or not).

**Comment by Highfoot** [comment]
@clchiou i would be really happy if an updated version of DosBox would be released for Chrome OS. Please? :smile:

**Comment by clchiou** [comment]
I haven't touched this project for quite some time and would need some time
to recall the details. Don't expect an update soon.

**Comment by wmwragg** [comment]
I opened this over 2 years ago, and as nothing has really happened with it, I'm going to close it. Anyone is welcome to reopen if they feel something will happen.

**Comment by clchiou** [comment]
I am sorry that I am not actively on this project.

**Comment by wmwragg** [comment]
It's cool, I was just doing some house keeping. I no longer own a Chromebook, that's why it took me so long to tidy up.

**Comment by koalaman** [comment]
If you're not bothered by it, just leave it open. Even if no one ever fixes it, it's useful as a form of documentation.

**Comment by MrScottyTay** [comment]
Did this ever get fixed I Can't seem to play any game that requires mouse like Dungeon Master (since chromebooks don't usually have numpads)

**Comment by clchiou** [comment]
I'm sorry but I'm not actively working on this project for a long time.
