### ISSUE TITLE
Use of serial port

### ISSUE THREAD

**Issue by acexbe** [clchiou/chrome-dosbox#4]
Just entered the chromeworld with a asus chromebook C720P.
Plugging in my USB to RS232 converter works on the native OS.
Tested this with the app Beagle Term.
The converter shows on the chromebook as /dev/ttyUSB0 connection Id 1.
Now I like to use this RS232 port from dosbox, so I added Serial1=directserial realport:com1 to the dosbox config.
However this does not work.
Is the config line faulty or is passing trough not possible?

**Comment by clchiou** [comment]
Hello,

I am sorry that as of today Native Client (the sandbox that runs DOSBox
inside Chrome) does not support serial port yet:
https://developer.chrome.com/native-client/faq

Regards,
Che-Liang
